<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sarm">

  <!-- Properties -->
  <xacro:property name="scale" value="0.001" />
  <xacro:property name="wheel_radius" value="${0.0325 * scale}" />
  <xacro:property name="wheel_width" value="${0.0304 * scale}" />
  <xacro:property name="total_width" value="${0.1994 * scale}" />
  <xacro:property name="total_height" value="${0.16225 * scale}" />
  <xacro:property name="base_length" value="${0.3 * scale}" />
  <xacro:property name="centered_length" value="${0.238 * scale}" />
  <xacro:property
        name="base_x_offset"
        value="${(centered_length - base_length)/2}"
    />
  <xacro:property name="base_size_x" value="${base_length}" />
  <xacro:property name="base_size_y" value="${total_width - 2 * wheel_width}" />
  <xacro:property
        name="base_size_z"
        value="${total_height - 2 * wheel_radius}"
    />
  <xacro:property name="base_mass" value="${4.6 * scale * scale * scale}" />

  <xacro:property name="wheel_xoff" value="0.05" />
  <xacro:property name="wheel_yoff" value="0.0" />
  <xacro:property name="wheel_separation" value="0.15" />
  <!-- Macro -->
  <xacro:macro name="sarm_base" params="prefix">
    <!-- Base footprint -->
    <link name="${prefix}base_footprint" />

    <!-- Base link -->
    <link name="${prefix}base_link">
      <visual>
        <geometry>
          <mesh
                        filename="file://$(find mec_mobile_description)/meshes/sarm/chassis.stl"
                        scale="${scale} ${scale} ${scale}"
                    />
        </geometry>
        <material name="white">
          <color rgba="1 1 1 1" />
        </material>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
        <origin
                    xyz="${base_x_offset} 0 ${base_size_z/2 + wheel_radius/4}"
                    rpy="0 0 0"
                />
      </collision>
      <inertial>
        <origin
                    xyz="${base_x_offset} 0 ${base_size_z/2 + wheel_radius/4}"
                    rpy="0 0 0"
                />
        <mass value="${base_mass}" />
        <inertia
                    ixx="${(1/12) * base_mass * ((base_size_y*base_size_y) + (base_size_z*base_size_z))}"
                    ixy="0.0"
                    ixz="0.0"
                    iyy="${(1/12) * base_mass * ((base_size_x*base_size_x) + (base_size_z*base_size_z))}"
                    iyz="0.0"
                    izz="${(1/12) * base_mass * ((base_size_x*base_size_x) + (base_size_y*base_size_y))}"
                />
      </inertial>
    </link>

    <!-- Gazebo visual -->
    <gazebo reference="${prefix}base_link">
      <visual>
        <material>
          <ambient>0 0.7 0 1</ambient>
          <diffuse>0 0.7 0 1</diffuse>
          <specular>0 0.7 0 1</specular>
        </material>
      </visual>
    </gazebo>

    <!-- Fixed joint to footprint -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link" />
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>
  </xacro:macro>

  <xacro:sarm_base prefix="sarm_" />

  <xacro:macro
        name="sarm_mecanum_wheel"
        params="prefix side x_reflect y_reflect"
    >
    <link name="${prefix}${side}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <mesh
                        filename="/home/ash-blake/lfr_ws/src/arena-robot-simulation/mec_mobile_description/meshes/sarm/visual/${side}_wheel.stl"
                    />
        </geometry>
        <material name="dark_gray">
          <color rgba="0.2 0.2 0.2 1.0" />
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>

    </link>

    <joint name="${prefix}${side}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${side}_wheel_link" />
      <origin
                xyz="${x_reflect*wheel_xoff} ${y_reflect*(wheel_separation/2+wheel_yoff)} ${-wheel_radius}"
                rpy="0 0 0"
            />
    </joint>

    <gazebo reference="${prefix}${side}_wheel_link">
      <surface>
        <friction>
          <ode>
              <mu>1.0</mu>
              <mu2>0.0</mu2>
          </ode>
        </friction>
      </surface>
      <visual>
          <material>
              <ambient>0.2 0.2 0.2 1.0</ambient>
              <diffuse>0.2 0.2 0.2 1.0</diffuse>
              <specular>0.2 0.2 0.2 1.0</specular>
              <emissive>0.0 0.0 0.0 0.0</emissive>
          </material>
      </visual>
  </gazebo>

  </xacro:macro>
</robot>
